name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/edgelesssys/edgelessrt-dev:ci

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: era

    - name: Test
      run: ertgo test ./...
      working-directory: era
