name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/edgelesssys/edgelessrt-dev:ci

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test
      run: go test ./...

    - name: Build
      run: go build -buildvcs=false
      working-directory: cmd/era

    - name: Build artifact
      uses: actions/upload-artifact@v2
      with:
        name: era
        path: cmd/era/era
